= A Guide to the Good Life
Nuno Campelo <campelo.nuno@gmail.com>
:toc:
:icons: font
:imagesDir: ../../resources/img

== Rise of Stoicism
____
Pre-Socratic philosiphy begins... with the discovery of Nature; Socratic philosophy begins with the discovery of *man's soul*
____

____
[Socrates] was as veritable paradigm of philosophical activity both in *thought* (theory) and in *deed* (pratical)
____

****
[.lead]
What you want out *of* life?
****

[CAUTION]
Not what you want *in* life sush as a caring spouse, good job or a nice house

.Philosophy of Life
. Help you identify a coerent grand goal in life
. Supply a strategy for attaining that goal

.Ancient philosofical subjects
* Physics +
The study of the natural world around us as well as the supernatural and relationship between them
* Logic +
Proper way to reason rationally persuade and refute arguments
* Ethics +
Eudaemonistic ethics from the Greek _good spirit_. Concerns not on what is right and wrong but on living a good, happy life. The pratical day to day aspects of the philosophy of life.

____
Stoic philosophy is like a fertile field,  with *Logic* being the encircling fence, *Ethics* the crop and *Physics* the soil
____

.Proeminent Ancient Schools
* Cyrenaics +
Grand goal in living was the experience of pleasure
* Cynics +
Eliminate all desire and possetions - ascetic lifestyle
* Stoic +
One should enjoy life without being enslaved by it

.Stoicism Aims
* Comtemplate the transitoty nature of the world around us
* Master your psyche and desires to attain tranquility and point them on a steady and favourable and joyfull course
* Be animated by a cheerful spirit that issues from deep within, that comes from being delighted by his own resources and desires no joys greater that hin inner joys

.Stoicism Foes
* Insatiability +
One way to go around taiming our tendency to always want more is to persuade ourselves to want the things we already have

.Stoicism Practices
* Negative visualization +
Spend time thinking about bad things that could happen to you so you can apreciate the good things you got going on in your life
* Voluntary disconfort +
Voluntarilly go without some of life's plesures so that you are not trapped thinking you can't live without or become addicted to them
* Layers of control
* Mindfull Introspection

.Stoic Virtues
Stoic virtue is concerned on how well one performs the function which one was designed to. Living in accordance with ones own nature. Since reason is what most distinguishes ourselfs from animals stoics believe that we were primarely design to be reasonable (and what follows from it)...

* Reasonable
    * Self-disciplined
    * Temperate
    * Diligent
    * Rational
    * Serene
* Social +
Honor our parents, be agreeable to our friends, and concerned with the interests of our countrymen
    ** Courageous
    ** Heroic
    ** Honored
    ** Agreeable
    ** Empatic
    ** Interested
    ** Caring
    ** Loving

